language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "5"
after_success: npm run coverage
env:
  - DATABASE_URL=postgres://localhost:5432/fl_migrations_test
services:
  - postgresql
before_script:
  - psql -c 'create database fl_migrations_test;' -U postgres
